name: stepsic
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - tabulate
  - numpy
  - matplotlib
  - scipy
  - h5py
  - astropy
  - camb
  - toml  # dead library, remove when we move to Python 3.11+
  # nbodykit dependencies
  - gsl
  - openmpi
  - mpi4py
  - compilers
  - pip:
      - colossus
      - nbodykit
