'''
Consistency of the stereographic pushforward used by the PDS force kernel.

The StePS PDS kernels return the physical geodesic acceleration as a 4D tangent t at q
(t _|_ q), then map it into the conformally-flat stereographic chart that the drift
integrates in.  The exact Jacobian of  x = R q_{1:3}/(1+q0)  is

    dx_i = ( R*t_{i+1} - x_i*t_0 ) / Omega,     Omega = 1 + q0 = 2R^2/(R^2+r^2)

and StePS absorbs the overall R into the kernel normalization, i.e. it evaluates
( t_{i+1} - (x_i/R)*t_0 ) / Omega  with  x_i/R = q_{i+1}/Omega.

These tests pin that formula down *without running a simulation*.  Historically the
kernel dropped the t_0 term (up to ~5% error at the domain boundary) and, before that,
the whole 1/Omega factor (~50%), while the same full Jacobian was already implemented
correctly for velocities in pds_stereo_vel_transform() / pds.stereo_vel_transform.

Run with:  python -m pytest tests/test_stereo_pushforward.py -v
'''
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from stepsic import pds  # noqa: E402

R_CURV = 3100.0
R_DOMAIN = 0.1584 * R_CURV        # PDS fundamental-domain face inradius, stereographic


def _random_domain_points(n, rng, rmax=R_DOMAIN):
    x = rng.normal(size=(n, 3))
    x /= np.linalg.norm(x, axis=1, keepdims=True)
    x *= rng.uniform(1.0, rmax, size=(n, 1))
    return x


def _steps_pushforward(q, t):
    '''The map StePS applies (R absorbed into the kernel normalization).'''
    inv_omega = 1.0 / (1.0 + q[..., 0:1])
    return (t[..., 1:] - q[..., 1:] * t[..., 0:1] * inv_omega) * inv_omega


def test_pushforward_matches_numeric_jacobian():
    '''The analytic pushforward equals the numerically differentiated stereographic
    map along the geodesic generated by t.'''
    rng = np.random.default_rng(0)
    x = _random_domain_points(200, rng)
    q = pds.inverse_stereo(x, R_CURV)
    q /= np.linalg.norm(q, axis=1, keepdims=True)

    worst = 0.0
    for i in range(len(q)):
        # a unit tangent at q[i], perpendicular to it
        t = rng.normal(size=4)
        t -= (t @ q[i]) * q[i]
        t /= np.linalg.norm(t)

        # move along the great circle through q[i] in direction t
        h = 1e-6
        qp = np.cos(h) * q[i] + np.sin(h) * t
        qm = np.cos(h) * q[i] - np.sin(h) * t
        numeric = (pds.stereo_project(qp[None], R_CURV)[0]
                   - pds.stereo_project(qm[None], R_CURV)[0]) / (2 * h) / R_CURV

        analytic = _steps_pushforward(q[i], t)
        worst = max(worst, np.abs(numeric - analytic).max()
                    / max(np.abs(numeric).max(), 1e-300))
    assert worst < 1e-8, f'pushforward disagrees with numeric Jacobian by {worst:.2e}'


def test_pushforward_agrees_with_velocity_transform():
    '''The force pushforward must be the same linear map already used for velocities.

    pds.stereo_vel_transform maps a stereographic velocity through a group element;
    with the identity element it reduces to (dq/dx)^-1 composed with (dx/dq), so
    pushing a stereographic vector to the tangent space and back must be the identity.
    That round-trip is exactly the Jacobian the force path must use.'''
    rng = np.random.default_rng(1)
    x = _random_domain_points(300, rng)
    q = pds.inverse_stereo(x, R_CURV)
    q /= np.linalg.norm(q, axis=1, keepdims=True)

    # inverse-stereo Jacobian applied to a stereographic vector v gives a tangent u;
    # pushing u forward with the force formula must return v.
    v = rng.normal(size=x.shape)
    r2 = np.sum(x * x, axis=1, keepdims=True)
    D = R_CURV ** 2 + r2
    xv = np.sum(x * v, axis=1, keepdims=True)
    u = np.concatenate([-4.0 * R_CURV ** 2 * xv / D ** 2,
                        2.0 * R_CURV * (D * v - 2.0 * x * xv) / D ** 2], axis=1)

    back = _steps_pushforward(q, u) * R_CURV
    assert np.abs(back - v).max() / np.abs(v).max() < 1e-10


def test_dropping_t0_is_detected_and_bounded():
    '''Guards the specific historical regression: omitting the t_0 term.

    Also pins its size, so the documented magnitude cannot silently drift again
    (it scales as (r/R)^2, reaching ~5% at the domain boundary -- not the ~30%
    once claimed in the PDS guide, nor the ~7% of the 2026-07 review).'''
    rng = np.random.default_rng(2)
    x = _random_domain_points(400, rng)
    q = pds.inverse_stereo(x, R_CURV)
    q /= np.linalg.norm(q, axis=1, keepdims=True)

    t = rng.normal(size=(len(q), 4))
    t -= np.sum(t * q, axis=1, keepdims=True) * q
    t /= np.linalg.norm(t, axis=1, keepdims=True)

    full = _steps_pushforward(q, t)
    dropped = t[:, 1:] / (1.0 + q[:, 0:1])          # the pre-fix expression
    rel = np.linalg.norm(full - dropped, axis=1) / np.linalg.norm(full, axis=1)

    assert rel.max() > 1e-3, 'the t_0 term is not actually being exercised'
    assert rel.max() < 0.10, f'error grew unexpectedly large: {rel.max():.3f}'

    # The error is the (r/R)^2 geometric term, so it must grow with radius.  Compare
    # binned medians rather than a raw correlation: at fixed r the size still depends
    # on the tangent's orientation, which dilutes a Pearson coefficient (~0.73) even
    # though the radial trend is monotonic and spans two orders of magnitude.
    r = np.linalg.norm(x, axis=1)
    edges = np.linspace(0.0, R_DOMAIN, 6)
    medians = [np.median(rel[(r >= lo) & (r < hi)])
               for lo, hi in zip(edges[:-1], edges[1:])]
    assert all(b > a for a, b in zip(medians, medians[1:])), \
        f'error is not monotonic in radius: {medians}'
    assert medians[-1] > 20 * medians[0], \
        f'radial growth too weak to be the (r/R)^2 term: {medians}'


if __name__ == '__main__':
    for name, fn in sorted(globals().items()):
        if name.startswith('test_'):
            fn()
            print(f'{name}: PASS')
