#!/usr/bin/env python3
'''
Plot the stepsic vs monofonIC cross-validation figure.

Produces a three-panel ratio figure (single A&A column) from the
``.npz`` archive generated by :mod:`compare-monofonic-run`:

    Panel (a): Power spectrum ratio  P_stepsic(k) / P_monofonic(k)
    Panel (b): Displacement histogram ratio  N_stepsic / N_monofonic
    Panel (c): Velocity histogram ratio      N_stepsic / N_monofonic

All three panels share the same visual language: a horizontal reference
line at 1.0, a shaded tolerance band, and the measured ratio curve.

Usage
-----
::

    python compare-monofonic-plot.py \\
        -i output/monofonic_comparison.npz \\
        -o output/validation-monofonic.pdf
'''

from __future__ import annotations

import argparse
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import matplotlib.pyplot as plt
import numpy as np

from validation import setup_matplotlib, load_archive

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__name__)


def _draw_ratio_panel(
    ax: plt.Axes,
    x: np.ndarray,
    ratio: np.ndarray,
    *,
    panel_label: str,
    ylabel_title: str,
    xlabel: str,
    ylim: tuple[float, float] = (0.99, 1.01),
    percent_band: float = 0.005,
    logx: bool = False,
    color: str = 'C0',
    k_ny: float | None = None,
    mask_low_counts: np.ndarray | None = None,
) -> None:
    '''Draw a single ratio panel.'''
    # Reference line and tolerance band
    ax.axhline(1.0, color='k', lw=0.8, ls=':', zorder=1)
    ax.axhspan(
        1.0 - percent_band, 1.0 + percent_band,
        color='grey', alpha=0.10, zorder=0,
    )

    # The ratio curve. For histogram ratios, mask bins whose count is
    # below a small fraction of the peak (Poisson noise blows up the
    # ratio in the distribution tails otherwise).
    if mask_low_counts is not None:
        peak = float(np.max(mask_low_counts))
        threshold = max(20.0, 0.01 * peak)
        good = mask_low_counts >= threshold
        x_plot = x[good]
        ratio_plot = ratio[good]
    else:
        x_plot = x
        ratio_plot = ratio

    if logx:
        ax.semilogx(x_plot, ratio_plot, '-', lw=1.0, color=color, zorder=3)
    else:
        ax.plot(x_plot, ratio_plot, '-', lw=1.0, color=color, zorder=3)

    # Nyquist marker (panel a only)
    if k_ny is not None:
        ax.axvline(
            k_ny, color='grey', ls=':', lw=0.6, alpha=0.5, zorder=2,
        )
        ax.annotate(
            rf'$k_{{\mathrm{{Ny}}}}$',
            xy=(k_ny, 0.1),
            xycoords=ax.get_xaxis_transform(),
            fontsize=6, color='grey', rotation=90,
            ha='right', va='bottom',
        )

    ax.set_ylim(*ylim)
    ax.set_xlabel(xlabel, fontsize=9)
    ax.set_title(ylabel_title, loc='left', fontsize=9)

    ax.text(
        0.03, 0.91, panel_label,
        transform=ax.transAxes, fontsize=8,
        va='top', ha='left',
    )


def _safe_ratio(a: np.ndarray, b: np.ndarray) -> np.ndarray:
    '''Elementwise a/b, returning NaN where b is zero.'''
    ratio = np.full_like(a, np.nan, dtype=np.float64)
    mask = b > 0
    ratio[mask] = a[mask] / b[mask]
    return ratio


def plot_comparison(
    data: dict,
    output: str | None = None,
    *,
    ylim_pk: tuple[float, float] = (0.98, 1.02),
    ylim_disp: tuple[float, float] = (0.9, 1.1),
    ylim_vel: tuple[float, float] = (0.9, 1.1),
    percent_band_pk: float = 0.01,
    percent_band_field: float = 0.01,
) -> None:
    '''
    Produce the three-panel comparison figure.

    Parameters
    ----------
    data : dict
        Archive contents from :func:`load_archive`.
    output : str or None
        Save path. Shows interactively if ``None``.
    '''
    setup_matplotlib()

    n_panels = 3
    panel_height = 1.25  # inches
    fig_width = 3.46     # A&A single column
    fig_height = n_panels * panel_height + 0.35

    fig, axes = plt.subplots(
        n_panels, 1,
        figsize=(fig_width, fig_height),
        sharex=False,
        gridspec_kw={'hspace': 0.9},
    )

    k_ny = float(data['meta_k_ny'])

    # -- Panel (a): P(k) ratio --
    k = data['pk_k']
    pk_ratio = data['pk_ratio']

    _draw_ratio_panel(
        axes[0], k, pk_ratio,
        panel_label='(a)',
        ylabel_title=r'$P_{\mathrm{stepsic}}(k)\, /\, P_{\mathrm{monofonIC}}(k)$',
        xlabel=r'$k$ [$h\,\mathrm{Mpc}^{-1}$]',
        ylim=ylim_pk,
        percent_band=percent_band_pk,
        logx=True,
        color='C0',
        k_ny=k_ny,
    )

    # -- Panel (b): Displacement histogram ratio --
    disp_centres = data['hist_disp_mag_centres']
    h_disp_s = data['hist_disp_mag_stepsic']
    h_disp_m = data['hist_disp_mag_monofonic']
    disp_ratio = _safe_ratio(h_disp_s, h_disp_m)
    disp_min_counts = h_disp_m

    _draw_ratio_panel(
        axes[1], disp_centres, disp_ratio,
        panel_label='(b)',
        ylabel_title=(
            r'$N_{\mathrm{stepsic}}(|\mathbf{\Psi}|)\, /\, '
            r'N_{\mathrm{monofonIC}}(|\mathbf{\Psi}|)$'
        ),
        xlabel=r'$|\mathbf{\Psi}|$ [$h^{-1}\,\mathrm{kpc}$]',
        ylim=ylim_disp,
        percent_band=percent_band_field,
        logx=False,
        color='tab:red',
        mask_low_counts=disp_min_counts,
    )

    # -- Panel (c): Velocity histogram ratio --
    vel_centres = data['hist_vel_mag_centres']
    h_vel_s = data['hist_vel_mag_stepsic']
    h_vel_m = data['hist_vel_mag_monofonic']
    vel_ratio = _safe_ratio(h_vel_s, h_vel_m)
    vel_min_counts = h_vel_m

    _draw_ratio_panel(
        axes[2], vel_centres, vel_ratio,
        panel_label='(c)',
        ylabel_title=(
            r'$N_{\mathrm{stepsic}}(|\mathbf{v}|)\, /\, '
            r'N_{\mathrm{monofonIC}}(|\mathbf{v}|)$'
        ),
        xlabel=r'$|\mathbf{v}|$ [km\,s$^{-1}$]',
        ylim=ylim_vel,
        percent_band=percent_band_field,
        logx=False,
        color='tab:green',
        mask_low_counts=vel_min_counts,
    )

    # Annotate summary statistics on each panel (lower-left).
    stat_labels = [
        ('pk_ratio', axes[0]),
        ('stat_disp_rel_median', axes[1]),
        ('stat_vel_rel_median', axes[2]),
    ]
    for key, ax in stat_labels:
        if key == 'pk_ratio':
            med = np.nanmedian(pk_ratio)
            ax.text(
                0.03, 0.08,
                rf'median$={med:.6f}$',
                transform=ax.transAxes, fontsize=6,
                ha='left', va='bottom', color='grey',
            )
        elif key in data:
            val = float(data[key])
            ax.text(
                0.03, 0.08,
                rf'median rel.$={val:.2e}$',
                transform=ax.transAxes, fontsize=6,
                ha='left', va='bottom', color='grey',
            )

    fig.tight_layout()

    if output:
        fig.savefig(output, bbox_inches='tight')
        log.info('Figure saved to %s', output)
    else:
        plt.show()


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description='Plot stepsic vs monofonIC 3-panel comparison.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument('-i', '--input', type=str, required=True,
                   help='Input .npz archive from compare-monofonic-run.py.')
    p.add_argument('-o', '--output', type=str, default=None,
                   help='Output figure path (e.g. validation-monofonic.pdf).')
    p.add_argument('--ylim-pk', type=float, nargs=2, default=[0.98, 1.02],
                   help='Y-axis limits for P(k) panel.')
    p.add_argument('--ylim-disp', type=float, nargs=2, default=[0.98, 1.02],
                   help='Y-axis limits for displacement panel.')
    p.add_argument('--ylim-vel', type=float, nargs=2, default=[0.98, 1.02],
                   help='Y-axis limits for velocity panel.')
    return p.parse_args()


if __name__ == '__main__':
    args = parse_args()
    data = load_archive(args.input)

    log.info(
        'Loaded comparison: %d^3 particles, %dLPT, z=%g',
        int(data['meta_nmesh']),
        int(data['meta_lpt_order']),
        float(data['meta_redshift']),
    )

    plot_comparison(
        data, output=args.output,
        ylim_pk=tuple(args.ylim_pk),
        ylim_disp=tuple(args.ylim_disp),
        ylim_vel=tuple(args.ylim_vel),
    )